.\" Manpage for fast_io::concat
.\" Contact euloanty@live.com or pssvv4@gmail.com to correct errors of typos
.TH CONCAT 3 2020-11-20 "fast_io" "C++ Programmer's Manual"
.SH "NAME"
native_file, inative_file, onative_file, ionative_file, u8native_file, u8inative_file, u8onative_file, u8ionative_file, wnative_file, winative_file, wonative_file, wionative_file - native file file observer.
.SH "SYNOPSIS"
.nf
.B #include <fast_io_device.h>
.PP
.BI "using native_file =   /* Depending on platform*/ "
.BI "using inative_file = input_file_wrapper<native_file>;"
.BI "using onative_file = output_file_wrapper<native_file>;"
.BI "using ionative_file = io_file_wrapper<native_file>;"
.PP
.BI "using u8native_file = /* Depending on platform */"
.BI "using u8inative_file = input_file_wrapper<u8native_file>; "
.BI "using u8onative_file = output_file_wrapper<u8native_file>; "
.BI "using u8ionative_file = io_file_wrapper<u8inative_file>; "
.PP
.BI "using wnative_file = /* Depending on platform */ "
.BI "using winative_file = input_file_wrapper<wnative_file>; "
.BI "using wonative_file = output_file_wrapper<wnative_file>; "
.BI "using wionative_file = io_file_wrapper<wnative_file>; "
.PP
.SH INITIALIZATION
list common usages only:
.PP
.BI "native_file file(filename, open_mode, permission); " 
.PP
.BI "native_file file(at_entry, filename, open_mode, permission);"
.PP
the default permission is 436.
.PP
.SH DESCRIPTION
native_file is an alias of current platform native file. Depending on your platform, native_file can be an alias of either
.BR win32_file
or
.BR posix_file.
.PP
An inative_file is equal to native_file with open mode fast_io::open_mode::in
.PP
A onative_file is equal to native_file with open mode fast_io::open_mode::out
.PP
An ionative_file is equal to native_file with open mode both fast_io::open_mode::in and fast_io::open_mode::out.
.PP
.SH RETURN VALUE
.BR native_file have no return value. It's a observer.
.SH THREAD SAFETY
If native_file is shared by multiple threads, operations on native_file shall be protected by mutex. native_file doesn't guarantee for thread safety. 
.PP
fast_io provides thread-safe files: 
.BR ibuf_file_mutex ,
.BR obuf_file_mutex
and 
.BR iobuf_file_mutex 
.PP
.SH PROCESS SAFETY
native_file guarantees for process safety.

.SH EXCEPTIONS
When failed to open/create native_file, it will throw exceptions.
.PP
.SH EXAMPLE
create or open (if such a file already exists) a file "text.txt" and write string "It's a sunny day!\n" (if such file exists, append this string). 
.PP
.in +8n
.EX
#include <fast_io.h>
#include <fast_io_device.h>

int main()
{
	std::string str("It's a sunny ");
	fast_io::native_file file("text.txt",  fast_io::open_mode::out | fast_io::open_mode::app);
	print(file, str, "day!\n");    
}
.EE
.in -8n
.PP
Open an existing local file "text.txt" and read one line at a time, until the end of the file:
.PP
.in +8n
.EX
#include <fast_io.h>
#include <fast_io_device.h>

int main()
{
	fast_io::native_file file("text.txt", fast_io::open_mode::in);
	for(std::string str;scan<true>(file, fast_io::line(str)); println(str));
}
.EE
.in -8n
.PP
Get file status of file "text.txt":
.in +8n
.EX
#include <fast_io.h>
#include <fast_io_device.h>

int main()
{
	fast_io::ionative_file nfl("text.txt");
    auto st{status(nfl)};

    println("status of text.txt:\n", st);
}
.EE
.in -8n

.SH SEE ALSO
.BR open_mode (3),
.BR status (3),
.BR to_span (3),
.BR native_pipe (3),
.BR dir_file (3),
.BR win32_file (3),
.BR posix_file (3),
.BR ibuf_file (3),
.BR obuf_file (3),
.BR iobuf_file (3),
.BR ibuf_file_mutex (3),
.BR obuf_file_mutex (3),
.BR iobuf_file_mutex (3),
.BR ibuf_text_file (3),
.BR obuf_text_file (3),
.BR basic_ibuf_utf (3),
.BR basic_obuf_utf (3),
.BR basic_ibuf_utf_file (3),
.BR basic_obuf_utf_file (3),
.BR ibuf_utf8_file (3),
.BR obuf_utf8_file (3),
.BR native_memory_map_file (3)
.SH COLOPHON
This page is part of 2628 version of the
.I fast_io
project.
Wiki can be found out in https://github.com/expnkx/fast_io/wiki
